version: '3.4'

services:
  mssqldb:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  mizekar-accounts:
    image: ${DOCKER_REGISTRY-}mizekar-accounts
    build:
      context: .
      dockerfile: src/Mizekar.Accounts/Dockerfile
    environment:
      ElasticConfigurationUri: http://elasticsearch:9200/
      db_connection: Server=mssqldb;Database=Mizekar.Accounts;User=sa;Password=Your_password123;
      db_connection_ids_config: Server=mssqldb;Database=Mizekar.Identity;User=sa;Password=Your_password123;
      db_connection_ids_operations: Server=mssqldb;Database=Mizekar.IdentityData;User=sa;Password=Your_password123;
      public_origin: http://docker.for.win.localhost:56000
    depends_on:
      - mssqldb
  mizekar-mvcclients:
    image: ${DOCKER_REGISTRY-}mizekar-mvcclients
    build:
      context: .
      dockerfile: src/Mizekar.MvcClients/Dockerfile
    depends_on:
      - mizekar-accounts
  mizekar-api:
    image: ${DOCKER_REGISTRY-}mizekar-api
    build:
      context: .
      dockerfile: src/Mizekar.Api/Dockerfile

volumes:
  elasticsearch-data:


